---
# Run with ansible-playbook <filename> -k
#   (make sure to add the IPs of machines you want to manage to /etc/ansible/hosts first)

- hosts: all
  tasks:  
   - name: reload nginx 
     service: name=nginx state=started #stopped #restarted #reloaded

