
  
---


- name: Replace default /etc/hosts file with configured hosts file from templates
  template: src=hosts  dest=/etc/hosts
    #owner: root
    #group: root
    #mode: 0744


- name: Replace default /etc/hostname file with configured hostname file from templates
  template: src=hostname dest=/etc/hostname
  

- name: install MySQL-python
  package:
    name: MySQL-python
    state: present




- name: Install the latest verion of centos-release-openstack-ocata
  package:
    name: centos-release-openstack-ocata
    state: present

- name: upgrade all packages
  yum: name=* state=latest



- name: COMMON | Install basic packages
  package: name={{ item }} state=present
  with_items:
    - python-openstackclient
    - openstack-selinux
    - mariadb
    - mariadb-server
    - python2-PyMySQL

- name: Create and edit the/etc/my.cnf.d/openstack.cnf file
  template: src=openstack.cnf dest=/etc/my.cnf.d/openstack.cnf


- name: enable mariadb
  command: systemctl enable mariadb.service
  notify: start mariadb
  ignore_errors: yes


- name: Install the latest verion of Rabbitmq-server
  package:
    name: rabbitmq-server
    state: latest

- name: enable rabbitmq-server
  command: systemctl enable rabbitmq-server.service
  #notify: start rabbitmq-server
- command: systemctl start rabbitmq-server.service

- name: Create rabbitmq user "openstack" and giving user full permissions.
  rabbitmq_user:
    user: openstack
    password: RABBIT_PASS
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: COMMON | Install memcached and python-memcached
  package: name={{ item }} state=present
  with_items:
    - memcached
    - python-memcached


- name: replace line
  lineinfile:
    dest: /etc/sysconfig/memcached
    regexp: '^(.*)OPTIONS="-l 127.0.0.1,::1"(.*)$'
    line: 'OPTIONS="-l 127.0.0.1,::1,controller"'
    backrefs: yes

- name: enable memcached
  become: root
  command: systemctl enable memcached.service
  notify: start memcached

- name: Set root user password
  # If .my.cnf already exists, this will cause an mysql-root-password update.
  mysql_user:
    login_user: root
    login_password: and345
    name: root
    password: "{{ mysql_root_password}}"
    check_implicit_admin: true

- name: Create .my.cnf
  template:
   src: "client.my.cnf.j2"
   dest: "/root/.my.cnf"
   owner: root
   group: root
   mode: 700

- name: Create a new database with name 'keystone'
  mysql_db:
    name: keystone
    state: present


- name: give permissions to keystone database
  mysql_user:
    name: keystone
    password: "{{keystone_password}}"
    priv: '*.*:ALL,GRANT'
    #host_all: yes
    state: present

- name: COMMON | Install openstack-keystone httpd mod_wsgi
  package: name={{ item }} state=present
  with_items:
    - openstack-keystone
    - httpd
    - mod_wsgi

- name: Edit the/etc/keystone/keystone.conf file
  template: src=keystone.conf  dest=/etc/keystone/keystone.conf


# - name: Populate the Identity service database
#   become_user: sudo 
# - name: Sync Keystone database
# - command: keystone-manage db_sync
#   become: yes
#   become_user: keystone
#   ignore_errors: yes

- command: su -s /bin/sh -c "keystone-manage db_sync" keystone
  #become_method: su 


- name: initialize Fernet key repositories - 1
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- name: initialize Fernet key repositories - 2
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

- command: keystone-manage bootstrap --bootstrap-password ADMIN_PASS --bootstrap-admin-url http://controller:35357/v3/  --bootstrap-internal-url http://controller:5000/v3/  --bootstrap-public-url http://controller:5000/v3/  --bootstrap-region-id RegionOne
 

- name: Adding ServerName "controller" to httpd.conf file
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: 'ServerName controller'


- name: enable httpd
  command: systemctl enable httpd.service
  notify: start httpd

# - command: ln -s /usr/share/keystone/wsgi-keystone.conf /etc/httpd/conf.d/ 
#   ignore_errors: yes


################################## CREATING OPENSTACK PROJECT USERS AND ROLES ###################################################

- template: src=admin-openrc.sh dest=/root/ owner=root mode=0600

- name: Creating a project named 'Service'
  shell: source /root/admin-openrc.sh && openstack project list | grep 'service' || openstack project create --domain default  --description "Service Project" service
  ignore_errors: yes
  
- name: Creating a project named 'Demo'
  shell: source /root/admin-openrc.sh && openstack project list | grep 'demo' || openstack project create --domain default  --description "Demo Project" demo
  ignore_errors: yes
  
- name: Creating a user named 'demo'
  shell: source /root/admin-openrc.sh && openstack user list| grep 'demo' || openstack user create --password and345 demo
  ignore_errors: yes
  
- name: Creating a role named 'user'
  shell: source /root/admin-openrc.sh && openstack role list | grep 'user' || openstack role create user 
  ignore_errors: yes
 
- name: Add the user role to the demo user of the demo project
  shell: source /root/admin-openrc.sh && openstack role add --project demo --user demo user 
  ignore_errors: yes
 
- name: Replace default /etc/keystone/keystone-paste.ini file with configured 'keystone-paste.ini' file from templates
  template: src=keystone-paste.ini dest=/etc/keystone/keystone-paste.ini
  

- name: Unset unset OS_AUTH_URL OS_PASSWORD
  raw: unset OS_AUTH_URL OS_PASSWORD
  ignore_errors: yes

# - name: token for admin
#   shell: source /root/admin-openrc.sh && openstack --os-auth-url http://controller:35357/v3  --os-project-domain-name default --os-user-domain-name default  --os-project-name admin  --os-username admin --os-password ADMIN_PASS token issue

# - name: token for demo
#   shell: source /root/admin-openrc.sh && openstack --os-auth-url http://controller:5000/v3  --os-project-domain-name default --os-user-domain-name default  --os-project-name demo --os-username demo --os-password and345 token issue


##################################################### GLANCE CONFIG ##############################################################

- name: Create a new database with name 'glance'
  mysql_db:
    name: glance
    state: present


- name: give permissions to keystone database
  mysql_user:
    name: glance
    password: and345
    priv: '*.*:ALL,GRANT'
    state: present


- name: give permissions to keystone database
  mysql_user:
    name: glance
    password: and345
    priv: '*.*:ALL,GRANT'
    host_all: yes
    state: present



- name: create glance user
  shell: source /root/admin-openrc.sh && openstack user list| grep 'glance' || openstack user create --domain default --password and345 glance


- name: Add theadmin role to the glance user andservice  project
  shell: source /root/admin-openrc.sh && openstack role add --project service --user glance admin


- name: Create a glance service entity 
  shell: source /root/admin-openrc.sh && openstack service list | grep 'glance' || openstack service create --name glance  --description "OpenStack Image" image


# - name: create end points for public internal and admin ####NEEDS MORE WORK########
#   shell: source /root/admin-openrc.sh && openstack endpoint create --region RegionOne  image public http://controller:9292
# - shell: source /root/admin-openrc.sh && openstack endpoint create --region RegionOne  image internal http://controller:9292
# - shell: source /root/admin-openrc.sh && openstack endpoint create --region RegionOne  image admin http://controller:9292



- name: Install openstack-glance 
  package:
    name: openstack-glance
    state: present


- name: Replace /etc/glance/glance-api.conf wih template conf file
  template: src=glance-api.conf  dest=/etc/glance/glance-api.conf

- name: Replace /etc/glance/glance-registry.conf wih template conf file
  template: src=glance-registry.conf  dest=/etc/glance/glance-registry.conf


- name: Populate the image database
  command: su -s /bin/sh -c "glance-manage db_sync" glance
  ignore_errors: yes 


- name: enable glance api serivce 
  command: systemctl enable openstack-glance-api.service 


- command: systemctl start openstack-glance-api.service


- name: enable glance register service 
  command: systemctl enable openstack-glance-registry.service
  
- command: systemctl start openstack-glance-registry.service

- name: Download Image 
  get_url: url=http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img dest=/root/cirros-0.3.5-x86_64-disk.img mode=0440

- name: Upload Image 
  shell: source /root/admin-openrc.sh && openstack image list | grep 'cirros' || openstack image create "cirros" --file cirros-0.3.5-x86_64-disk.img  --disk-format qcow2 --container-format bare  --public  < /root/cirros-0.3.5-x86_64-disk.img









