---

- name: Replace default /etc/hosts file with configured hosts file from templates
  template: src=hosts  dest=/etc/hosts
    #owner: root
    #group: root
    #mode: 0744


- name: Replace default /etc/hostname file with configured hostname file from templates
  template: src=hostname dest=/etc/hostname
  



- name: Install the latest version of Chrony 
  package:
    name: chrony
    state: latest

- name: enable chronyd 
  command: systemctl enable chronyd.service
  notify: restart chronyd


- name: Install the latest verion of centos-release-openstack-ocata
  package: 
    name: centos-release-openstack-ocata
    state: latest 

- name: upgrade all packages
  yum: name=* state=latest

- name: COMMON | Install basic packages 
  package: name={{ item }} state=present
  with_items:
    - python-openstackclient
    - openstack-selinux
    - mariadb
    - mariadb-server
    - python2-PyMySQL
    - memcached   
    
######MY SQL SECURE SETUP ALONG WITH MARIADB#######


# - name: Add configuration
#   template: src={{ mysql_conf_tpl }} dest={{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }} owner=root group=root mode=0644
#   when: mysql_conf_tpl != 'change_me'
#   notify: restart mysql

# - name: Start and enable service
#   service: name=mysql state=started enabled=yes

# - include: mysql_secure_installation.yml
#   when: mysql_secure_installation and mysql_root_password is defined



- name: Create and edit the/etc/my.cnf.d/openstack.cnf file
  template: src=openstack.cnf dest=/etc/my.cnf.d/openstack.cnf
 # owner: root
 # group: root 
 # mode: 0744
  

- name: enable mariadb
  command: systemctl enable mariadb.service
  
#- name: still fixing 
#  command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/ 
  
#- name: still fixing 
#  command: mysql_secure_installation
#  notify: start mariadb 

#- name: start mariadb
#  command: systemctl start mariadb.service

- name: rabbitmq-server 
  package: 
    name: rabbitmq-server
    state: latest 

- name: enable rabbitmq-server
  command: systemctl enable rabbitmq-server.service
  

- name: start rabbitmq-server
  command: systemctl start rabbitmq-server.service

#- name: add user
#  command: rabbitmqctl add_user openstack RABBIT_PASS
  
- name: set permissions
  command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"

- name: install memcached python-memcached
  package: 
    name: python-memcached
    state: latest 

- name: replace line
  lineinfile: 
    dest: /etc/sysconfig/memcached
    regexp: '^(.*)OPTIONS="-l 127.0.0.1,::1"(.*)$' 
    line: 'OPTIONS="-l 127.0.0.1,::1,controller"'
    backrefs: yes
  

- name: enable memcached
  command: sudo systemctl enable memcached.service 
  notify: start memcached
