---


- name: Replace default /etc/hostname file with configured "hostname" file from templates
  template: src=hostname dest=/etc/hostname



- name: Replace default /etc/hosts file with configured "hosts" file from templates
  template: src=hosts dest=/etc/hosts 



- name: Install the latest verion of centos-release-openstack-ocata
  package: 
    name: centos-release-openstack-ocata
    state: latest 


- name: COMMON | Install basic packages 
  package: name={{ item }} state=present
  with_items:
    - openstack-nova-compute 
    - openstack-selinux
    - openstack-neutron-linuxbridge
    - ebtables
    - ipset

- name: Replace default /etc/nova/nova.conf file with configured nova.conf file from templates
  template: src=nova.conf dest=/etc/nova.conf 

- name: enable libvirtd service 
  command: systemctl libvirtd.service openstack-nova-compute.service
  notify: start libvirtd 
  ignore_errors: yes 

- name: enable openstack-nova-compute service
  command: systemctl enable openstack-nova-compute.service
  notify: start openstack-nova-compute
  ignore_errors: yes 

  
- name: Replace default /etc/neutron/neutron.conf file with configured neutron.conf file from templates
  template: src=neutron.conf dest=/etc/neutron/neutron.conf 

- name: Replace default /etc/neutron/plugins/ml2/linuxbridge_agent.ini with configure linuxbridge_agent.ini file from templates 
  templates: src= linuxbridge_agent.ini dest= /etc/neutron/plugins/ml2/linuxbridge_agent.ini



- name: Replace default /etc/neutron/plugins/ml2/linuxbridge_agent.ini with configure linuxbridge_agent.ini file from templates 
  templates: src= linuxbridge_agent.ini dest= /etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: Restart openstack-nova-compute.service 
  notify: restart openstack-nova-compute
  gnore_errors: yes

