--- 


# - name: Create Datacenter
#   local_action:
#     module: vmware_datacenter
#     hostname: 129.119.125.37
#     username: administrator@vsphere.local
#     validate_certs: False
#     password: Dcnd@$mu123
#     datacenter_name: "TEST-DCDN"
#     state: present




- name: Clone a VM from Template and customize
  vmware_guest:
    hostname: 10.44.104.2
    username: administrator@vsphere.local
    password: Dcnd@$mu123
    validate_certs: no
    datacenter: DCND
    cluster: DCND-cluster
    name: testvm-2
    template: test
    networks:
    - name: VM Network
      ip: 10.44.104.200
      netmask: 255.255.255.0
      gateway: 10.44.104.1.
      #mac: aa:bb:dd:aa:00:14
      #domain: my_domain
      dns_servers:
      - 8.8.8.8
      - 10.44.104.25
 
    
      
  delegate_to: localhost





# # Clone a VM from Template and customize
#   - name: Clone template and customize
#     vmware_guest:
#       hostname: 129.119.125.37
#       username: administrator@vsphere.local
#       password: Dcnd@$mu123
#       validate_certs: no
#       datacenter: datacenter
#       cluster: cluster
#       name: testvm-2
#       template: CentOs-7
#       # networks:
#       # - name: VM Network
#       #   ip: 192.168.1.100
#       #   netmask: 255.255.255.0
#       #   gateway: 192.168.1.1
#       #   mac: 'aa:bb:dd:aa:00:14'
#       #   domain: my_domain
#       #   dns_servers:
#       #   - 192.168.1.1
#       #   - 192.168.1.2
#       # customization:
#       #   autologon: True
#       #   dns_servers:
#       #   - 192.168.1.1
#       #   - 192.168.1.2
#       #   domain: my_domain
#       #   password: new_vm_password
#       #   runonce:
#       #   - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\Enable-WinRM.ps1 -ForceNewSSLCert
