---


- name: COMMON | Install basic packages
  package: name={{ item }} state=present
  with_items:
    - git-core 
    - python-jinja2
    - python-paramiko
    - python-yaml
    - sshpass
    



- name: Git clone ansible from github repo (BLEEDING EDGE)
  git:
    repo: 'https://github.com/ansible/ansible'
    dest: /home/john-2/ansible
    clone: yes
    track_submodules: yes 
    update: yes 
    recursive: yes 
    force: yes 
  


- name: Update Submodules
  raw: (git submodule update --init --recurcive)